from: "admin@server.com"
to:	"you@exampl.com"
via:	"smtp"
address:	"mail.server.com"
port:	"587"
enable_starttls_auto: "true"
user_name: "user"
password:	"password"
authentication:	"plain"
domain:	"localhost.localdomain"
