development:
  adapter: sqlite3
  database: db/db.sqlite3
  timeout: 15000

production:
  adapter: 'postgresql'
  host: localhost
  port: 5432
  username: "user"
  password: "password"
  database: "db"
  encoding: 'utf8'

log_dir: "log"