Name: string   			# Name
Email: string     		# E-Mail-Adresse
Tel: string   			# Telefonnummer
EventDate: date    		# Veranstaltungsdatum
Start: time   			# Beginn der Veranstaltung
Strasse: string     	# Veranstaltungsort - Strasse
Ort: string   			# Veranstaltungsort - Stadt
AnzahlG: integer    	# Anzahl Gäste
AnzahlG20: integer  	# Anzahl Gäste unter 20 
AnzahlG60: integer  	# Anzahl Gäste über 60 
EquipExist: boolean 	# Equipment vorhanden
TechConsult: boolean	# Technik Beratung erwünscht
Kommentar: text   		# Sonstige Anmerkungen