datum: date    			# Veranstaltungsdatum
zeit: time   				# Beginn der Veranstaltung
dj_start_zeit: time	# Ab wann ein DJ auflegen soll
dj_ende_zeit: time 	# bis wann ein DJ auflegen soll
ort: string         # Veranstaltungsort - z.B. 'Bürgerhaus'
strasse: string     # Veranstaltungsort - Strasse
stadt: string   		# Veranstaltungsort - Stadt
anzahl: integer    	# Anzahl Gäste
anzahl20: integer  	# Anzahl Gäste unter 20 
anzahl60: integer  	# Anzahl Gäste über 60 
equipment: boolean 	# Equipment vorhanden
beratung: boolean		# Technik Beratung erwünscht
kommentar: text   	# Sonstige Anmerkungen
wish_id: integer 		# Wunsch Referenz
user_id: integer		# User Referenz